//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VkApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RequestItems {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequestItems() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VkApi.Resources.RequestItems", typeof(RequestItems).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;access_token=.
        /// </summary>
        internal static string accessToken {
            get {
                return ResourceManager.GetString("accessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;attachments=photo.
        /// </summary>
        internal static string attachPhoto {
            get {
                return ResourceManager.GetString("attachPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to createComment?.
        /// </summary>
        internal static string createComment {
            get {
                return ResourceManager.GetString("createComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete?.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit?.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getList?.
        /// </summary>
        internal static string getList {
            get {
                return ResourceManager.GetString("getList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getWallUploadServer?.
        /// </summary>
        internal static string getServer {
            get {
                return ResourceManager.GetString("getServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;hash=.
        /// </summary>
        internal static string hash {
            get {
                return ResourceManager.GetString("hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to likes..
        /// </summary>
        internal static string likes {
            get {
                return ResourceManager.GetString("likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;message=.
        /// </summary>
        internal static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;owner_id=.
        /// </summary>
        internal static string ownerId {
            get {
                return ResourceManager.GetString("ownerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;photo=.
        /// </summary>
        internal static string photo {
            get {
                return ResourceManager.GetString("photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photos..
        /// </summary>
        internal static string photos {
            get {
                return ResourceManager.GetString("photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post?.
        /// </summary>
        internal static string post {
            get {
                return ResourceManager.GetString("post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;post_id=.
        /// </summary>
        internal static string postId {
            get {
                return ResourceManager.GetString("postId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saveWallPhoto?.
        /// </summary>
        internal static string savePhoto {
            get {
                return ResourceManager.GetString("savePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;server=.
        /// </summary>
        internal static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;v=.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wall..
        /// </summary>
        internal static string wall {
            get {
                return ResourceManager.GetString("wall", resourceCulture);
            }
        }
    }
}
